// Script to translate remaining Vietnamese text to English
const translations = {
    // Task related
    'Chưa có task nào.': 'No tasks yet.',
    'Bạn chưa có task nào.': 'You have no tasks yet.',
    'Task': 'Task',
    'Mô tả': 'Description',
    'Người thực hiện': 'Assigned To',
    'Trạng thái': 'Status',
    'Deadline': 'Deadline',
    'Hành động': 'Actions',
    'Xem': 'View',
    'Sửa': 'Edit',
    'Sửa task': 'Edit Task',
    'Tạo task mới': 'Create New Task',
    'Tạo task': 'Create Task',
    'Tạo task mới cho nhóm': 'Create New Task for Group',
    
    // Modal titles and forms
    'Tạo dự án mới': 'Create New Project',
    'Tạo nhóm mới': 'Create New Group',
    'Tạo task mới': 'Create New Task',
    'Tạo đánh giá thành viên': 'Create Member Evaluation',
    'Tạo đánh giá thành viên - Nhóm': 'Create Member Evaluation - Group',
    'Chỉnh sửa Task': 'Edit Task',
    
    // Form labels
    'Tên dự án': 'Project Name',
    'Tên nhóm': 'Group Name',
    'Mô tả': 'Description',
    'Dự án': 'Project',
    'Chọn dự án': 'Select Project',
    'Chọn nhóm': 'Select Group',
    'Chọn nhóm muốn tham gia': 'Select Group to Join',
    'Trưởng nhóm': 'Group Leader',
    'Chọn trưởng nhóm': 'Select Group Leader',
    'Tên trưởng nhóm': 'Group Leader Name',
    'Người được đánh giá': 'Person to Evaluate',
    'Chọn người được đánh giá': 'Select Person to Evaluate',
    'Làm việc nhóm': 'Teamwork',
    'Trách nhiệm': 'Responsibility',
    'Chất lượng': 'Quality',
    'Đúng giờ': 'Punctuality',
    'Nhận xét': 'Comments',
    'Cho phép chỉnh sửa deadline': 'Allow deadline editing',
    'Trạng thái': 'Status',
    
    // Buttons
    'Tạo dự án': 'Create Project',
    'Tạo nhóm': 'Create Group',
    'Tạo task': 'Create Task',
    'Tạo đánh giá': 'Create Evaluation',
    'Thêm thành viên': 'Add Member',
    'Xóa': 'Remove',
    'Rời nhóm': 'Leave Group',
    'Xóa nhóm': 'Delete Group',
    'Chấp nhận': 'Approve',
    'Từ chối': 'Reject',
    'Hoàn thành': 'Complete',
    'Yêu cầu gia hạn': 'Request Extension',
    'Gia hạn': 'Extend',
    'In thông tin nhóm': 'Print Group Info',
    'Đóng': 'Close',
    'Hủy': 'Cancel',
    
    // Messages and alerts
    'Tạo dự án thành công!': 'Project created successfully!',
    'Tạo task thành công!': 'Task created successfully!',
    'Đã tạo đánh giá thành công!': 'Evaluation created successfully!',
    'Đã gửi yêu cầu tham gia nhóm!': 'Group join request sent!',
    'Đã chấp nhận yêu cầu tham gia nhóm!': 'Group join request approved!',
    'Đã từ chối yêu cầu tham gia nhóm!': 'Group join request rejected!',
    'Đã thêm thành viên vào nhóm!': 'Member added to group!',
    'Tên thành viên không hợp lệ hoặc đã tồn tại trong nhóm!': 'Invalid member name or already exists in group!',
    'Bạn có chắc chắn muốn xóa nhóm này?': 'Are you sure you want to delete this group?',
    'Không thể đánh giá chính mình!': 'Cannot evaluate yourself!',
    'Chưa có đánh giá nào cho nhóm này!': 'No evaluations for this group yet!',
    'Chưa có đánh giá nào cho bạn!': 'No evaluations for you yet!',
    'Bạn không có quyền chỉnh sửa task này!': 'You do not have permission to edit this task!',
    'Bạn không có quyền chỉnh sửa task này': 'You do not have permission to edit this task',
    
    // Evaluation related
    'Bảng đánh giá thành viên': 'Member Evaluation Board',
    'Đánh giá của tôi': 'My Evaluation',
    'Đánh giá cuối kỳ': 'Final Evaluation',
    'Đánh giá cuối kỳ -': 'Final Evaluation -',
    'Xem đánh giá cuối kỳ': 'View Final Evaluation',
    'Xem đánh giá': 'View Evaluation',
    'Xem đánh giá của tôi': 'View My Evaluation',
    'Tạo đánh giá thành viên': 'Create Member Evaluation',
    'Người đánh giá': 'Evaluator',
    'Người được đánh giá': 'Person Evaluated',
    'Điểm': 'Score',
    'Thống kê đánh giá': 'Evaluation Statistics',
    'Làm việc nhóm': 'Teamwork',
    'Trách nhiệm': 'Responsibility',
    'Chất lượng': 'Quality',
    'Đúng giờ': 'Punctuality',
    'Đánh giá tự động từ AI': 'Automatic evaluation from AI',
    'Không có nhận xét': 'No comments',
    
    // Statistics and reports
    'Thống kê thời gian làm việc': 'Work Time Statistics',
    'Thống kê tổng thể': 'Overall Statistics',
    'Tổng số dự án': 'Total Projects',
    'Tổng số nhóm': 'Total Groups',
    'Tổng số bài tập': 'Total Assignments',
    'Tổng số task': 'Total Tasks',
    'Task hoàn thành': 'Completed Tasks',
    '% đã hoàn thành': '% Completed',
    'Thời gian làm việc': 'Work Time',
    'Thống kê nhóm': 'Group Statistics',
    
    // File attachments
    'file đính kèm': 'attached files',
    'Không có file đính kèm': 'No attached files',
    
    // Comments and notes
    'Khi tạo nhóm, chỉ có leader là thành viên, không thêm member nào': 'When creating a group, only the leader is a member, no additional members',
    'Không mời ai khi tạo nhóm': 'No invitations when creating group',
    'Hiển thị bảng thông tin nhóm đã tạo': 'Display created group information table',
    'Hàm hiển thị modal tạo đánh giá thành viên': 'Function to display member evaluation creation modal',
    'Leader và member đều không thể đánh giá chính mình': 'Both leader and member cannot evaluate themselves',
    'Hàm tạo đánh giá thành viên': 'Function to create member evaluation',
    'Kiểm tra không đánh giá chính mình': 'Check not to evaluate yourself',
    'Lưu đánh giá vào localStorage hoặc biến global': 'Save evaluation to localStorage or global variable',
    'Hàm xem đánh giá thành viên': 'Function to view member evaluation',
    'Lọc đánh giá theo quyền': 'Filter evaluations by permission',
    'Member chỉ xem được đánh giá của chính mình': 'Member can only view their own evaluation',
    'Hàm tạo thống kê đánh giá': 'Function to create evaluation statistics',
    'Hàm xem chi tiết task': 'Function to view task details',
    'Kiểm tra quyền chỉnh sửa': 'Check edit permission',
    'Cập nhật thống kê nhóm nếu cần': 'Update group statistics if needed',
    'Lấy danh sách trưởng nhóm duy nhất': 'Get unique group leader list',
    'Hàm lọc nhóm theo trưởng nhóm': 'Function to filter groups by leader',
    'Reset lại chọn nhóm nếu nhóm đang chọn không thuộc leader đã chọn': 'Reset group selection if selected group does not belong to selected leader',
    'Gửi yêu cầu tham gia nhóm': 'Send group join request',
    'Chọn trưởng nhóm': 'Select Group Leader',
    'Chọn nhóm': 'Select Group',
    'Chọn nhóm muốn tham gia': 'Select Group to Join',
    'Lấy tất cả nhóm mà member tham gia': 'Get all groups that the member participates in',
    'Chỉ member mới kiểm tra lời mời nhóm': 'Only members check group invitations',
    'Lời mời tham gia nhóm': 'Group Invitations',
    'Yêu cầu tham gia nhóm': 'Group Join Requests',
    'Thông báo': 'Notifications',
    'Yêu cầu vào nhóm': 'Request to Join Group',
    'Nhóm hiện tại': 'Current Group',
    'Đề tài': 'Topic',
    'Trưởng nhóm': 'Group Leader',
    'Task của tôi trong nhóm này': 'My Tasks in This Group',
    'Tất cả task trong nhóm': 'All Tasks in Group',
    'Đánh giá thành viên': 'Member Evaluation',
    'Tạo đánh giá thành viên': 'Create Member Evaluation',
    'Xem đánh giá của tôi': 'View My Evaluation',
    'Bạn chưa tham gia nhóm nào.': 'You haven\'t joined any group yet.',
    'Quản lý dự án': 'Project Management',
    'Tạo dự án mới': 'Create New Project',
    'Tạo nhóm': 'Create Group',
    'Đánh giá tổng thể': 'Overall Evaluation',
    'Danh sách dự án': 'Project List',
    'Danh sách nhóm': 'Group List',
    'Yêu cầu tham gia nhóm': 'Group Join Requests',
    'Thống kê tổng thể': 'Overall Statistics',
    'Tổng số dự án': 'Total Projects',
    'Tổng số nhóm': 'Total Groups',
    'Tổng số bài tập': 'Total Assignments',
    'Tự động tạo deadline cho bài tập': 'Automatically create deadlines for assignments',
    'Đánh giá tự động thành viên': 'Automatic member evaluation',
    'Thống kê tổng thể': 'Overall statistics',
    'Chưa có dự án nào.': 'No projects yet.',
    'Chưa có nhóm nào.': 'No groups yet.',
    'Không có yêu cầu tham gia nhóm nào.': 'No group join requests.',
    'Thành viên': 'Member',
    'Nhóm': 'Group',
    'Tiến độ': 'Progress',
    'Members': 'Members',
    'Actions': 'Actions',
    'View': 'View',
    'Leave Group': 'Leave Group',
    'Approve': 'Approve',
    'Reject': 'Reject',
    'No tasks yet.': 'No tasks yet.',
    'Description': 'Description',
    'Assigned To': 'Assigned To',
    'Status': 'Status',
    'Edit': 'Edit',
    'Create New Task': 'Create New Task',
    'Create Task': 'Create Task',
    'Create New Task for Group': 'Create New Task for Group',
    'Project Name': 'Project Name',
    'Group Name': 'Group Name',
    'Select Project': 'Select Project',
    'Select Group': 'Select Group',
    'Select Group to Join': 'Select Group to Join',
    'Group Leader': 'Group Leader',
    'Select Group Leader': 'Select Group Leader',
    'Group Leader Name': 'Group Leader Name',
    'Person to Evaluate': 'Person to Evaluate',
    'Select Person to Evaluate': 'Select Person to Evaluate',
    'Teamwork': 'Teamwork',
    'Responsibility': 'Responsibility',
    'Quality': 'Quality',
    'Punctuality': 'Punctuality',
    'Comments': 'Comments',
    'Allow deadline editing': 'Allow deadline editing',
    'Create Project': 'Create Project',
    'Create Group': 'Create Group',
    'Create Evaluation': 'Create Evaluation',
    'Add Member': 'Add Member',
    'Remove': 'Remove',
    'Delete Group': 'Delete Group',
    'Complete': 'Complete',
    'Request Extension': 'Request Extension',
    'Extend': 'Extend',
    'Print Group Info': 'Print Group Info',
    'Close': 'Close',
    'Cancel': 'Cancel',
    'Project created successfully!': 'Project created successfully!',
    'Task created successfully!': 'Task created successfully!',
    'Evaluation created successfully!': 'Evaluation created successfully!',
    'Group join request sent!': 'Group join request sent!',
    'Group join request approved!': 'Group join request approved!',
    'Group join request rejected!': 'Group join request rejected!',
    'Member added to group!': 'Member added to group!',
    'Invalid member name or already exists in group!': 'Invalid member name or already exists in group!',
    'Are you sure you want to delete this group?': 'Are you sure you want to delete this group?',
    'Cannot evaluate yourself!': 'Cannot evaluate yourself!',
    'No evaluations for this group yet!': 'No evaluations for this group yet!',
    'No evaluations for you yet!': 'No evaluations for you yet!',
    'You do not have permission to edit this task!': 'You do not have permission to edit this task!',
    'You do not have permission to edit this task': 'You do not have permission to edit this task',
    'Member Evaluation Board': 'Member Evaluation Board',
    'My Evaluation': 'My Evaluation',
    'Final Evaluation': 'Final Evaluation',
    'View Final Evaluation': 'View Final Evaluation',
    'View Evaluation': 'View Evaluation',
    'View My Evaluation': 'View My Evaluation',
    'Create Member Evaluation': 'Create Member Evaluation',
    'Evaluator': 'Evaluator',
    'Person Evaluated': 'Person Evaluated',
    'Score': 'Score',
    'Evaluation Statistics': 'Evaluation Statistics',
    'Automatic evaluation from AI': 'Automatic evaluation from AI',
    'No comments': 'No comments',
    'Work Time Statistics': 'Work Time Statistics',
    'Overall Statistics': 'Overall Statistics',
    'Total Projects': 'Total Projects',
    'Total Groups': 'Total Groups',
    'Total Assignments': 'Total Assignments',
    'Total Tasks': 'Total Tasks',
    'Completed Tasks': 'Completed Tasks',
    '% Completed': '% Completed',
    'Work Time': 'Work Time',
    'Group Statistics': 'Group Statistics',
    'attached files': 'attached files',
    'No attached files': 'No attached files',
    'When creating a group, only the leader is a member, no additional members': 'When creating a group, only the leader is a member, no additional members',
    'No invitations when creating group': 'No invitations when creating group',
    'Display created group information table': 'Display created group information table',
    'Function to display member evaluation creation modal': 'Function to display member evaluation creation modal',
    'Both leader and member cannot evaluate themselves': 'Both leader and member cannot evaluate themselves',
    'Function to create member evaluation': 'Function to create member evaluation',
    'Check not to evaluate yourself': 'Check not to evaluate yourself',
    'Save evaluation to localStorage or global variable': 'Save evaluation to localStorage or global variable',
    'Function to view member evaluation': 'Function to view member evaluation',
    'Filter evaluations by permission': 'Filter evaluations by permission',
    'Member can only view their own evaluation': 'Member can only view their own evaluation',
    'Function to create evaluation statistics': 'Function to create evaluation statistics',
    'Function to view task details': 'Function to view task details',
    'Web Programming Team Statistics - Website Project': 'Web Programming Team Statistics - Website Project',
    'Member Contribution Statistics': 'Member Contribution Statistics',
    'Tasks Assigned': 'Tasks Assigned',
    'Tasks Completed': 'Tasks Completed',
    'Completion Rate (%)': 'Completion Rate (%)',
    'Group information not found': 'Group information not found',
    'Check edit permission': 'Check edit permission',
    'Update group statistics if needed': 'Update group statistics if needed',
    'Get unique group leader list': 'Get unique group leader list',
    'Function to filter groups by leader': 'Function to filter groups by leader',
    'Reset group selection if selected group does not belong to selected leader': 'Reset group selection if selected group does not belong to selected leader',
    'Send group join request': 'Send group join request',
    'Get all groups that the member participates in': 'Get all groups that the member participates in',
    'Only members check group invitations': 'Only members check group invitations',
    'Group Invitations': 'Group Invitations',
    'Notifications': 'Notifications',
    'Request to Join Group': 'Request to Join Group',
    'Current Group': 'Current Group',
    'Topic': 'Topic',
    'My Tasks in This Group': 'My Tasks in This Group',
    'All Tasks in Group': 'All Tasks in Group',
    'Member Evaluation': 'Member Evaluation',
    'You haven\'t joined any group yet.': 'You haven\'t joined any group yet.',
    'Project Management': 'Project Management',
    'Create New Project': 'Create New Project',
    'Overall Evaluation': 'Overall Evaluation',
    'Project List': 'Project List',
    'Group List': 'Group List',
    'Overall Statistics': 'Overall Statistics',
    'Automatically create deadlines for assignments': 'Automatically create deadlines for assignments',
    'Automatic member evaluation': 'Automatic member evaluation',
    'Overall statistics': 'Overall statistics',
    'No projects yet.': 'No projects yet.',
    'No groups yet.': 'No groups yet.',
    'No group join requests.': 'No group join requests.',
    'Member': 'Member',
    'Group': 'Group',
    'Progress': 'Progress'
};

// Function to replace Vietnamese text with English
function translateText(text) {
    for (const [vietnamese, english] of Object.entries(translations)) {
        text = text.replace(new RegExp(vietnamese, 'g'), english);
    }
    return text;
}

console.log('Translation script loaded. Use translateText() function to translate Vietnamese text to English.'); 